<?php

namespace ContainerOnah2j6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSiteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1SOZ5Ms.App\Entity\Site' shared service.
     *
     * @return \App\Entity\Site
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1SOZ5Ms": it references class "App\\Entity\\Site" but no such service exists.');
    }
}
