<?php

namespace ContainerK5PiZ59;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiliereService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.scg7lsC.App\Entity\Filiere' shared service.
     *
     * @return \App\Entity\Filiere
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.scg7lsC": it references class "App\\Entity\\Filiere" but no such service exists.');
    }
}
