<?php

namespace ContainerU0rND5i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1SOZ5MsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1SOZ5Ms' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1SOZ5Ms'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'site' => ['privates', '.errored..service_locator.1SOZ5Ms.App\\Entity\\Site', NULL, 'Cannot autowire service ".service_locator.1SOZ5Ms": it references class "App\\Entity\\Site" but no such service exists.'],
        ], [
            'site' => 'App\\Entity\\Site',
        ]);
    }
}
