<?php

namespace ContainerCylniUR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VCt9qy4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCt9qy4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCt9qy4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filiereRepository' => ['privates', 'App\\Repository\\FiliereRepository', 'getFiliereRepositoryService', true],
        ], [
            'filiereRepository' => 'App\\Repository\\FiliereRepository',
        ]);
    }
}
