<?php

namespace ContainerCylniUR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Scg7lsCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.scg7lsC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.scg7lsC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'filiere' => ['privates', '.errored..service_locator.scg7lsC.App\\Entity\\Filiere', NULL, 'Cannot autowire service ".service_locator.scg7lsC": it references class "App\\Entity\\Filiere" but no such service exists.'],
        ], [
            'filiere' => 'App\\Entity\\Filiere',
        ]);
    }
}
